### ISSUE TITLE
Comments and replies

### ISSUE THREAD

**Issue by P17160065** [DMU-CTEC2902/APGBSU-Repo#7]
Every comment should allow other users to reply to create a dialogue between users

**Comment by RhysCruz** [comment]
Some helpful links
https://stackoverflow.com/questions/48568771/adding-comment-to-post-in-asp-net-mvc

**Comment by RhysCruz** [comment]
https://stackoverflow.com/questions/9292544/how-to-add-comment-to-mvc-application
